name: practice_scrollable_widget
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0


dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  cached_network_image: ^3.4.1
  flutter_slidable: ^4.0.0
  equatable: ^2.0.5
  get_it: ^8.0.3
  retrofit: ^4.4.2
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  injectable: ^2.5.0
dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.5.0
  json_serializable: ^6.8.0
  freezed: ^3.0.6
  injectable_generator: ^2.7.0


flutter:
  uses-material-design: true
  generate: true
